--- #YAML:1.0
name:               Finance-Quote-Sberbank
version:            0.04
abstract:           Obtain quotes from Sberbank (Savings Bank of
author:
    - Alexander Korolyoff <kilork@yandex.ru>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Finance::Quote:       0
    Spreadsheet::ParseExcel:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
